server:
  port: 5001
  
spring:
  application:
    name: microservice-config
  cloud:
    config:
      server:
        git:  
          uri: https://github.com/1574432191/microservice-cloud-config.git